[project]
name = "wordnet-conceptnet-mapping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nltk>=3.9.1",
    "requests>=2.32.4",
]
