[project]
name = "content-to-form"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deep-translator>=1.11.4",
    "dotenv>=0.9.9",
    "nltk>=3.9.1",
    "pandas>=2.3.0",
]
